package com.service.notification_service.websocket.dto;

public enum NotificationType {
    ORDER_CREATED,
    ORDER_STATUS_UPDATED,
    ORDER_CANCELLED,
    RESERVATION_CREATED,
    LOW_STOCK_ALERT,
    OUT_OF_STOCK_ALERT,
    STOCK_RECEIVED,
    REVENUE_REPORT,
    SYSTEM_ALERT,
    // Shift assignment events
    SHIFT_ASSIGNMENT_CREATED,
    SHIFT_ASSIGNMENT_UPDATED,
    SHIFT_ASSIGNMENT_APPROVED,
    SHIFT_ASSIGNMENT_REJECTED,
    SHIFT_ASSIGNMENT_DELETED,
    SHIFT_ASSIGNMENT_CHECKED_IN,
    SHIFT_ASSIGNMENT_CHECKED_OUT,
    // Shift request events
    SHIFT_REQUEST_LEAVE_CREATED,
    SHIFT_REQUEST_SWAP_CREATED,
    SHIFT_REQUEST_OVERTIME_CREATED,
    SHIFT_REQUEST_APPROVED,
    SHIFT_REQUEST_REJECTED,
    SHIFT_REQUEST_CANCELLED,
    SHIFT_REQUEST_TARGET_RESPONDED,
    // Shift publish events
    SHIFT_PUBLISHED,
    // Shift draft events (simplified - notify on draft changes)
    SHIFT_DRAFT_CREATED,
    SHIFT_DRAFT_UPDATED,
    SHIFT_DRAFT_DELETED
}

