package com.service.profile.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
public enum ErrorCode {
    UNCATEGORIZED_EXCEPTION(9999, "Uncategorized error", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_KEY(1001, "Uncategorized error", HttpStatus.BAD_REQUEST),
    EMAIL_EXISTED(1002, "Email existed", HttpStatus.BAD_REQUEST),
    EMAIL_INVALID(1003, "Email must be valid", HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD(1004, "Password must be at least {min} characters", HttpStatus.BAD_REQUEST),
    EMPTY_PASSWORD(1005, "Password is required", HttpStatus.BAD_REQUEST),
    EMPTY_EMAIL(1006, "Email is required", HttpStatus.BAD_REQUEST),
    EMPTY_FULLNAME(1007, "Fullname is required", HttpStatus.BAD_REQUEST),
    EMPTY_PHONE_NUMBER(1008, "Phone number is required", HttpStatus.BAD_REQUEST),
    EMAIL_NOT_EXISTED(1007, "Email not existed", HttpStatus.NOT_FOUND),
    UNAUTHENTICATED(1008, "Unauthenticated", HttpStatus.UNAUTHORIZED),
    UNAUTHORIZED(1007, "You do not have permission", HttpStatus.FORBIDDEN),
    INVALID_DOB(1009, "Your age must be at least {min}", HttpStatus.BAD_REQUEST),
    EMPTY_TOKEN(1010, "Token is required", HttpStatus.BAD_REQUEST),
    ROLE_NOT_FOUND(1011, "Role not found", HttpStatus.NOT_FOUND),
    INVALID_ROLE(1012, "Invalid role", HttpStatus.BAD_REQUEST),
    INVALID_PHONE_NUMBER(1013, "Phone number must be valid", HttpStatus.BAD_REQUEST),
    PHONE_NUMBER_SIZE(1014, "Phone number must be at least {min} characters", HttpStatus.BAD_REQUEST),
    ACCESS_DENIED(1015, "Access denied", HttpStatus.FORBIDDEN),
    EMPTY_LABEL(1016, "Label is required", HttpStatus.BAD_REQUEST),
    INVALID_LABEL(1017, "Label must be at most {max} characters", HttpStatus.BAD_REQUEST),
    EMPTY_FULL_ADDRESS(1018, "Full address is required", HttpStatus.BAD_REQUEST),
    INVALID_FULL_ADDRESS(1019, "Full address must be at most {max} characters", HttpStatus.BAD_REQUEST),
    LABEL_EXISTED(1020, "Label existed", HttpStatus.BAD_REQUEST),
    EMPTY_USER_ID(1021, "User id is required", HttpStatus.BAD_REQUEST),
    EMPTY_DOB(1022, "Dob is required", HttpStatus.BAD_REQUEST),
    USER_ID_EXISTED(1023, "User id existed", HttpStatus.BAD_REQUEST),
    EMPTY_BRANCH_ID(1024, "Branch id is required", HttpStatus.BAD_REQUEST),
    EMPTY_IDENTITY_CARD(1025, "Identity card is required", HttpStatus.BAD_REQUEST),
    EMPTY_POSITION(1026, "Position is required", HttpStatus.BAD_REQUEST),
    EMPTY_HIRE_DATE(1027, "Hire date is required", HttpStatus.BAD_REQUEST),
    EMPTY_SALARY(1028, "Salary is required", HttpStatus.BAD_REQUEST),
    EMPTY_BASE_SALARY(1029, "Base salary is required for MONTHLY pay type", HttpStatus.BAD_REQUEST),
    EMPTY_HOURLY_RATE(1030, "Hourly rate is required for HOURLY pay type", HttpStatus.BAD_REQUEST),
    VALIDATION_FAILED(4000, "Validation failed", HttpStatus.BAD_REQUEST),
    USER_ID_NOT_FOUND(4001, "User id not found", HttpStatus.NOT_FOUND),
    BRANCH_NOT_FOUND(4002, "Branch not found", HttpStatus.NOT_FOUND),
    IDENTITY_CARD_EXISTED(4003, "Identity card existed", HttpStatus.BAD_REQUEST),
    IDENTITY_CARD_NUMERIC_ONLY(4004, "Identity card must be numeric only", HttpStatus.BAD_REQUEST),
    IDENTITY_CARD_SIZE(4005, "Identity card must be at least {min} characters", HttpStatus.BAD_REQUEST),
    USER_NOT_ASSIGNED_TO_BRANCH(4006, "User not assigned to branch", HttpStatus.BAD_REQUEST),
    EMPTY_MANAGER_USER_ID(4007, "Manager user id is required", HttpStatus.BAD_REQUEST),
    MANAGER_ASSIGNED_TO_BRANCH(4008, "Manager assigned to branch, please unassign the manager from the branch first",
            HttpStatus.BAD_REQUEST),
    ADDRESS_NOT_FOUND(4009, "Address not found", HttpStatus.NOT_FOUND),
    SHIFT_TEMPLATE_NOT_FOUND(4010, "Shift template not found", HttpStatus.NOT_FOUND),
    INVALID_TIME_RANGE(4011, "startTime must be before endTime", HttpStatus.BAD_REQUEST),
    SHIFT_NOT_FOUND(4012, "Shift not found", HttpStatus.NOT_FOUND),
    EXTERNAL_SERVICE_ERROR(4013, "External service error: {message}", HttpStatus.BAD_GATEWAY),
    SHIFT_TIME_OVERLAP(4014, "Shift time overlaps with existing shift on the same date", HttpStatus.BAD_REQUEST),
    NO_SHIFTS_TO_PUBLISH(4015, "No DRAFT shifts found to publish in the selected range", HttpStatus.BAD_REQUEST),
    NO_SHIFTS_TO_CANCEL(4016, "No future shifts found to cancel in the selected range", HttpStatus.BAD_REQUEST),
    SHIFT_NOT_PUBLISHED(4017, "Shift is not in PUBLISHED status and cannot be reverted to DRAFT", HttpStatus.BAD_REQUEST),
    SHIFT_HAS_ASSIGNMENTS(4018, "Cannot revert shift to draft because it has staff assignments", HttpStatus.BAD_REQUEST),
    SHIFT_ASSIGNMENT_NOT_FOUND(4019, "Shift assignment not found", HttpStatus.NOT_FOUND),
    SHIFT_NOT_AVAILABLE(4020, "Shift is not available for registration", HttpStatus.BAD_REQUEST),
    SHIFT_ALREADY_REGISTERED(4021, "You have already registered for this shift", HttpStatus.BAD_REQUEST),
    SHIFT_FULL(4022, "Shift is full (max staff reached)", HttpStatus.BAD_REQUEST),
    SHIFT_TIME_CONFLICT(4023, "This shift conflicts with another shift you are assigned to", HttpStatus.BAD_REQUEST),
    SHIFT_EXCEEDS_DAILY_HOURS(4024, "Registering for this shift would exceed 8 hours per day limit", HttpStatus.BAD_REQUEST),
    SHIFT_EXCEEDS_WEEKLY_HOURS(4025, "Registering for this shift would exceed 40 hours per week limit", HttpStatus.BAD_REQUEST),
    SHIFT_INSUFFICIENT_REST(4026, "Registering for this shift violates 11-hour rest period requirement", HttpStatus.BAD_REQUEST),
    SHIFT_EMPLOYMENT_TYPE_MISMATCH(4027, "This shift is not available for your employment type", HttpStatus.BAD_REQUEST),
    SHIFT_ROLE_NOT_QUALIFIED(4028, "You do not have the required role for this shift", HttpStatus.BAD_REQUEST),
    SHIFT_ROLE_FULL(4029, "This shift has reached the required number of staff for your role", HttpStatus.BAD_REQUEST),
    SHIFT_ASSIGNMENT_NOT_SELF_REGISTERED(4030, "This assignment was not self-registered and cannot be unregistered", HttpStatus.BAD_REQUEST),
    SHIFT_ASSIGNMENT_ALREADY_CONFIRMED(4031, "This assignment is already confirmed and cannot be unregistered", HttpStatus.BAD_REQUEST),
    // Additional shift validation errors
    SHIFT_EXCEEDS_DAILY_SHIFTS(4032, "Maximum {max} shifts per day allowed", HttpStatus.BAD_REQUEST),
    SHIFT_EXCEEDS_WEEKLY_SHIFTS(4033, "Maximum {max} shifts per week allowed", HttpStatus.BAD_REQUEST),
    SHIFT_EXCEEDS_CONSECUTIVE_DAYS(4034, "Maximum {max} consecutive days allowed", HttpStatus.BAD_REQUEST),
    SHIFT_EXCEEDS_MAX_DURATION(4035, "Maximum shift duration is {max} hours", HttpStatus.BAD_REQUEST),
    SHIFT_BELOW_MIN_DURATION(4036, "Minimum shift duration is {min} hours", HttpStatus.BAD_REQUEST),
    SHIFT_MISSING_BREAK_TIME(4037, "Shifts longer than {hours} hours require at least {break} hours break time", HttpStatus.BAD_REQUEST),
    SHIFT_PATTERN_RESTRICTED(4038, "Shift pattern not allowed: {reason}", HttpStatus.BAD_REQUEST),
    SHIFT_EXCEEDS_OVERTIME_LIMIT(4039, "Maximum {max} hours overtime per week allowed", HttpStatus.BAD_REQUEST),
    SHIFT_EXCEEDS_DAILY_OVERTIME(4040, "Maximum {max} hours overtime per day allowed", HttpStatus.BAD_REQUEST),
    SHIFT_EXCEEDS_WEEKEND_LIMIT(4041, "Maximum {max} weekend day per week allowed", HttpStatus.BAD_REQUEST),
    SHIFT_DATE_IN_PAST(4042, "Cannot create shifts in the past", HttpStatus.BAD_REQUEST),
    SHIFT_DATE_TOO_FAR(4043, "Cannot create shifts more than {months} months in advance", HttpStatus.BAD_REQUEST),
    SHIFT_CROSS_BRANCH_NOT_ALLOWED(4044, "This shift does not allow cross-branch staff", HttpStatus.BAD_REQUEST),
    // Shift Request errors
    SHIFT_REQUEST_NOT_FOUND(4050, "Shift request not found", HttpStatus.NOT_FOUND),
    SHIFT_REQUEST_INVALID_TYPE(4051, "Invalid request type. Must be SWAP, PICK_UP, TWO_WAY_SWAP, LEAVE, or OVERTIME", HttpStatus.BAD_REQUEST),
    SHIFT_REQUEST_ALREADY_PROCESSED(4052, "This request has already been processed", HttpStatus.BAD_REQUEST),
    SHIFT_REQUEST_INVALID_ASSIGNMENT(4053, "Invalid assignment for this request", HttpStatus.BAD_REQUEST),
    SHIFT_REQUEST_SWAP_TARGET_REQUIRED(4054, "Target staff is required for SWAP/PICK_UP/TWO_WAY_SWAP request", HttpStatus.BAD_REQUEST),
    SHIFT_REQUEST_OVERTIME_HOURS_REQUIRED(4055, "Overtime hours is required for OVERTIME request", HttpStatus.BAD_REQUEST),
    SHIFT_REQUEST_SWAP_TARGET_NOT_AVAILABLE(4056, "Target staff is not available for swap", HttpStatus.BAD_REQUEST),
    SHIFT_REQUEST_SWAP_TARGET_SAME_STAFF(4057, "Cannot swap with yourself", HttpStatus.BAD_REQUEST),
    SHIFT_REQUEST_ASSIGNMENT_NOT_OWNED(4058, "You can only create requests for your own assignments", HttpStatus.FORBIDDEN),
    SHIFT_REQUEST_NOT_WAITING_FOR_TARGET(4059, "Request is not waiting for target approval", HttpStatus.BAD_REQUEST),
    SHIFT_REQUEST_ONLY_TARGET_CAN_RESPOND(4060, "Only target staff can respond to this request", HttpStatus.FORBIDDEN),
    SHIFT_REQUEST_MUST_BE_APPROVED_BY_TARGET(4061, "Request must be approved by target staff first", HttpStatus.BAD_REQUEST),
    SHIFT_REQUEST_PICK_UP_ASSIGNMENT_NOT_OWNED_BY_TARGET(4062, "Assignment must belong to target staff for PICK_UP request", HttpStatus.BAD_REQUEST),
    SHIFT_REQUEST_TWO_WAY_SWAP_TARGET_ASSIGNMENT_REQUIRED(4063, "Target staff assignment is required for TWO_WAY_SWAP request", HttpStatus.BAD_REQUEST),
    SHIFT_REQUEST_TWO_WAY_SWAP_TARGET_ASSIGNMENT_NOT_FOUND(4064, "Target staff does not have an assignment to swap", HttpStatus.BAD_REQUEST),
    SHIFT_REQUEST_LEAVE_DEADLINE_PASSED(4068, "Leave request must be submitted at least 12 hours before shift start time", HttpStatus.BAD_REQUEST),
    // Conflict resolution errors
    SHIFT_REQUEST_CIRCULAR_DETECTED(4065, "Circular request detected", HttpStatus.BAD_REQUEST),
    SHIFT_REQUEST_ASSIGNMENT_ALREADY_CANCELLED(4066, "Assignment has already been cancelled", HttpStatus.BAD_REQUEST),
    SHIFT_REQUEST_ASSIGNMENT_ALREADY_REASSIGNED(4067, "Assignment has already been reassigned", HttpStatus.BAD_REQUEST),
    // Check-in/Check-out errors
    SHIFT_CHECKIN_INVALID_STATUS(4070, "Can only check in for CONFIRMED or PENDING assignments", HttpStatus.BAD_REQUEST),
    SHIFT_CHECKIN_ALREADY_CHECKED_IN(4071, "You have already checked in for this shift", HttpStatus.BAD_REQUEST),
    SHIFT_CHECKIN_ALREADY_CHECKED_OUT(4072, "Cannot check in. You have already checked out", HttpStatus.BAD_REQUEST),
    SHIFT_CHECKIN_TOO_EARLY(4073, "Cannot check in. Too early. Check-in window opens 15 minutes before shift start", HttpStatus.BAD_REQUEST),
    SHIFT_CHECKIN_TOO_LATE(4074, "Cannot check in. Too late. Check-in window closed 15 minutes after shift start", HttpStatus.BAD_REQUEST),
    SHIFT_CHECKIN_SHIFT_NOT_STARTED(4075, "Cannot check in. Shift date is in the future", HttpStatus.BAD_REQUEST),
    SHIFT_CHECKIN_SHIFT_ENDED(4076, "Cannot check in. Shift has already ended", HttpStatus.BAD_REQUEST),
    SHIFT_CHECKOUT_NOT_CHECKED_IN(4077, "Cannot check out. You must check in first", HttpStatus.BAD_REQUEST),
    SHIFT_CHECKOUT_ALREADY_CHECKED_OUT(4078, "You have already checked out for this shift", HttpStatus.BAD_REQUEST),
    SHIFT_CHECKOUT_TOO_EARLY(4079, "Cannot check out. Too early. Check-out window opens 5 minutes before shift end", HttpStatus.BAD_REQUEST),
    SHIFT_CHECKOUT_MISSING_CHECKIN_TIME(4080, "Cannot check out. Check-in time is missing", HttpStatus.BAD_REQUEST),
    SHIFT_CHECKOUT_INVALID_TIME_RANGE(4081, "Invalid time range. Check-out time must be after check-in time", HttpStatus.BAD_REQUEST),
    SHIFT_CHECKOUT_INVALID_HOURS(4082, "Invalid hours calculated. Please contact manager", HttpStatus.BAD_REQUEST),
    SHIFT_INVALID_WORKING_HOURS(4083, "Shift time violates working hours regulations. Night shifts (22:00-06:00) require special approval", HttpStatus.BAD_REQUEST),
    // Payroll errors
    PAYROLL_ALREADY_EXISTS(5000, "Payroll already exists for this user and period", HttpStatus.BAD_REQUEST),
    PAYROLL_NOT_FOUND(5001, "Payroll not found", HttpStatus.NOT_FOUND),
    PAYROLL_ALREADY_APPROVED(5002, "Payroll already approved, cannot be modified", HttpStatus.BAD_REQUEST),
    PAYROLL_ALREADY_PAID(5003, "Payroll already paid, cannot be modified", HttpStatus.BAD_REQUEST),
    INVALID_PERIOD_FORMAT(5004, "Period must be in format YYYY-MM", HttpStatus.BAD_REQUEST),
    EMPTY_PERIOD(5005, "Period is required", HttpStatus.BAD_REQUEST),
    BONUS_NOT_FOUND(5010, "Bonus not found", HttpStatus.NOT_FOUND),
    PENALTY_NOT_FOUND(5020, "Penalty not found", HttpStatus.NOT_FOUND),
    ALLOWANCE_NOT_FOUND(5030, "Allowance not found", HttpStatus.NOT_FOUND),
    // Template errors
    TEMPLATE_NOT_FOUND(5040, "Template not found", HttpStatus.NOT_FOUND),
    ALLOWANCE_TEMPLATE_NOT_FOUND(5041, "Allowance template not found", HttpStatus.NOT_FOUND),
    BONUS_TEMPLATE_NOT_FOUND(5042, "Bonus template not found", HttpStatus.NOT_FOUND),
    PENALTY_CONFIG_NOT_FOUND(5043, "Penalty config not found", HttpStatus.NOT_FOUND),
    TEMPLATE_ACCESS_DENIED(5044, "You do not have access to this template", HttpStatus.FORBIDDEN),
    EMPTY_NAME(5045, "Name is required", HttpStatus.BAD_REQUEST),
    EMPTY_ALLOWANCE_TYPE(5046, "Allowance type is required", HttpStatus.BAD_REQUEST),
    EMPTY_BONUS_TYPE(5047, "Bonus type is required", HttpStatus.BAD_REQUEST),
    EMPTY_PENALTY_TYPE(5048, "Penalty type is required", HttpStatus.BAD_REQUEST),
    INVALID_AMOUNT(5049, "Amount must be positive", HttpStatus.BAD_REQUEST),
    DUPLICATE_ENTITY(5050, "Duplicate entity already exists", HttpStatus.BAD_REQUEST),
    ;

    ErrorCode(int code, String message, HttpStatusCode statusCode) {
        this.code = code;
        this.message = message;
        this.statusCode = statusCode;
    }

    private final int code;
    private final String message;
    private final HttpStatusCode statusCode;

    public HttpStatus getHttpStatus() {
        return (HttpStatus) statusCode;
    }
}
